// Add any additional repositories for your dependencies here

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = 'jitpack.io'
        url = 'https://jitpack.io'
        content {
            includeGroup "com.github.CrucibleMC"
        }
    }
}
